version: "3.3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${WP_MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${WP_MYSQL_DATABASE}"
      MYSQL_USER: "${WP_MYSQL_USER}"
      MYSQL_PASSWORD: "${WP_MYSQL_PASSWORD}"
    volumes:
      - ./var/lib/mysql:/var/lib/mysql

  app:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${WP_MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${WP_MYSQL_PASSWORD}"
    ports:
      - "${WP_PORT}:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
